---
title: "Data Analysis.rmd"
author: "Christopher O'Donnell"
date: "5/5/2022"
output: html_document
---

```{r setup, include=FALSE}
cereal_data <- readr::read_csv(here::here("data", "cereal-health-cleandata-csv.csv"))
library(ggplot2)
library(tidyverse)
install.packages("psych")
library(psych)
library(dplyr)
knitr::opts_chunk$set(echo = TRUE)
```

###Overview of cleaned statistics in R

summary(cereal_data0

view(cereal_data)

print(cereal_data)

###Scatterplot comparing sugar(g) amount between each mfr

cereal_data |>
ggplot(aes(x= mfr,
        y= sugars, color = mfr, fill= mfr))+
        geom_point(size=5)+
        geom_line()
        
        
###Boxplot with individual statistics focused on giving clear data on calorie counts in differnet cereals, colored and sorted by mfr
        
ggplot(na.omit(cereal_data)) +
  aes(y = mfr,
      x = calories,
      color = mfr,
      fill = mfr) +
  geom_jitter(height = .3) +
  geom_boxplot(color = "black",
               alpha = .3,
               width = .2,
               size = .5) 
  
  
###Summary Table detailing averages of all cereals independent of mfr (nothing worth noting gathered)
describe(cereal_data)
 
 
####Scatterplot with individual points giving amounts of potassium within cereal sorted by mfr
 
ggplot(cereal_data,
      aes(x= mfr, y = potass, color = mfr)) +
      geom_point()+
      geom_jitter(height = 0, width = .4)
      
df %>%
    group_by(mfr) %>%
    summarise_at(vars(sugars), list(name = mean))

  
Mfr Key
G = General Mills
K = Kelloggs
N = Nabisco
P = Post
Q = Quaker Oats
R = Ralston Purina
  
####It can be understood that the Manufacturer (mfr) of the cereal oftentimes does have a correlation to the health statistics. When looking at all three plots, it is apparent that Nabisco by far is the healthiest cereal manufacturer holding the lowest mean calories and sugar. Along with this, it is easy to see that all other cereal manufacturers are attempting to maintain similar statistics. When looking at the histograms for calories, it is very apparent that these manufacturers are likely attempting to meet similar health statistics. However, Quaker Oats also stands out as an outlier with lower average calories and sugar than most other manufacturers. 

####When looking at potassium, it can be noted that certain brands like General Mills don't make effort into incorportating more. On the flipside, it is notable that mfrs like Post and Nabisco have multiple cereals with high potassium amounts. Overall, this data analysis has proven that there are health correlations between the cereal manufacturer and their cereal products.
        
